

package com.tunjid.snapshottable.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.tunjid.snapshottable.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("arrays.kt")
  public void testArrays() {
    run("arrays.kt");
  }

  @Test
  @TestMetadata("collections.kt")
  public void testCollections() {
    run("collections.kt");
  }

  @Test
  @TestMetadata("complex_types.kt")
  public void testComplex_types() {
    run("complex_types.kt");
  }

  @Test
  @TestMetadata("data_class_methods.kt")
  public void testData_class_methods() {
    run("data_class_methods.kt");
  }

  @Test
  @TestMetadata("default_values.kt")
  public void testDefault_values() {
    run("default_values.kt");
  }

  @Test
  @TestMetadata("enums_sealed.kt")
  public void testEnums_sealed() {
    run("enums_sealed.kt");
  }

  @Test
  @TestMetadata("extra_properties.kt")
  public void testExtra_properties() {
    run("extra_properties.kt");
  }

  @Test
  @TestMetadata("generics.kt")
  public void testGenerics() {
    run("generics.kt");
  }

  @Test
  @TestMetadata("generics_sealed_bound.kt")
  public void testGenerics_sealed_bound() {
    run("generics_sealed_bound.kt");
  }

  @Test
  @TestMetadata("generics_user_bound.kt")
  public void testGenerics_user_bound() {
    run("generics_user_bound.kt");
  }

  @Test
  @TestMetadata("inheritance.kt")
  public void testInheritance() {
    run("inheritance.kt");
  }

  @Test
  @TestMetadata("nested_classes.kt")
  public void testNested_classes() {
    run("nested_classes.kt");
  }

  @Test
  @TestMetadata("nullable.kt")
  public void testNullable() {
    run("nullable.kt");
  }

  @Test
  @TestMetadata("recursive.kt")
  public void testRecursive() {
    run("recursive.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    run("simple.kt");
  }
}
